import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SessionProvider from "@/components/common/SessionProvider";
import { auth } from "@/lib/auth.js";
import NavBar from "@/components/NavBar";
import ProviderWrapper from "@/components/common/dynamic-wrapper.js";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  if (session?.user) {
    // filter out sensitive data before passing to client.
    session.user = {
      name: session.user.name,
      email: session.user.email,
      image: session.user.image,
    };
  }
  return (
    <html lang="en">
      <ProviderWrapper>
        <SessionProvider session={session}>
          <body className={inter.className}>
            <NavBar />
            {children}
          </body>
        </SessionProvider>
      </ProviderWrapper>
    </html>
  );
}
